# Assignment OF data science 
Add two columns High_Low_Speed and High_Low_HP

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("pokemon.csv")
data.head(n=10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [17]:
data.tail(n=10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,HP_high_low
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False,HP Low
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False,HP High
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True,HP High
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True,HP High
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True,HP High
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,HP Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,HP Low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,HP High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,HP High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,HP High

In [10]:
data["HP"].mean()

69.25875

# Feature Engineering
Add Column

# High_Low_HP

In [12]:
hp_mean =data["HP"].mean()

def hp_set(val):
    if val < hp_mean:
        return "HP Low"
    elif val == hp_mean:
        return "HP Netural"
    else:
        return "HP High"

In [16]:
# "HP_high_low"  -> "HP High" , "HP Low"
data ["HP_high_low"]= data["HP"].apply(hp_set)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,HP_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,HP Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,HP Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,HP High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,HP High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,HP Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,HP Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,HP Low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,HP High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,HP High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,HP High

# High_Low_Speed

In [18]:
data["HP"].mean()

69.25875

In [19]:
speed_mean =data["HP"].mean()

def speed_set(val):
    if val < speed_mean:
        return "speed Low"
    elif val == speed_mean:
        return "speed Netural"
    else:
        return "speed High"

In [20]:
# "Speed_high_low"  -> "Speed High" , "Speed Low"
data ["Speed_high_low"]= data["Speed"].apply(speed_set)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,HP_high_low,Speed_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,HP Low,speed Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,HP Low,speed Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,HP High,speed High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,HP High,speed High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,HP Low,speed Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,HP Low,speed Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,HP Low,speed High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,HP High,speed High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,HP High,speed High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,HP High,speed High

# #################The End of Assignment#################